<a href="https://colab.research.google.com/github/ojaspaul123/ML-Experiments/blob/main/ML_Projects/Movie%20Recommendation%20System/Movie_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import pandas as pd
import numpy as np

In [40]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("bhargavchirumamilla/netflix-movies-and-tv-shows-till-2025")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'netflix-movies-and-tv-shows-till-2025' dataset.
Path to dataset files: /kaggle/input/netflix-movies-and-tv-shows-till-2025

In [41]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("victorsoeiro/hbo-max-tv-shows-and-movies")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'hbo-max-tv-shows-and-movies' dataset.
Path to dataset files: /kaggle/input/hbo-max-tv-shows-and-movies

In [42]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("victorsoeiro/amazon-prime-tv-shows-and-movies")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'amazon-prime-tv-shows-and-movies' dataset.
Path to dataset files: /kaggle/input/amazon-prime-tv-shows-and-movies

In [43]:
%%markdown
---
Data Load

---
Data Load

In [44]:
from google.colab import files
uploaded = files.upload()
df_netflix_movies = pd.read_csv('netflix_movies.csv')
df_netflix_movies.head()

Saving netflix_movies.csv to netflix_movies (1).csv

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average,budget,revenue
0,10192,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,NaN,"Comedy, Adventure, Fantasy, Animation, Family",en,A bored and domesticated Shrek pacts with deal...,203.893,7449,6.380,165000000,752600867
1,27205,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,NaN,"Action, Science Fiction, Adventure",en,"Cobb, a skilled thief who commits corporate es...",156.242,37119,8.369,160000000,839030630
2,12444,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,NaN,"Adventure, Fantasy",en,"Harry, Ron and Hermione walk away from their l...",121.191,19327,7.744,250000000,954305868
3,38757,Movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.600,NaN,"Animation, Family, Adventure",en,"Feisty teenager Rapunzel, who has long and mag...",111.762,11638,7.600,260000000,592461732
4,10191,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.800,NaN,"Fantasy, Adventure, Animation, Family",en,As the son of a Viking leader on the cusp of m...,110.044,13259,7.800,165000000,494879471

In [45]:
from google.colab import files
uploaded = files.upload()
df_netflix_TV = pd.read_csv('netflix_tv_shows.csv')
df_netflix_TV.head()

Saving netflix_tv_shows.csv to netflix_tv_shows (1).csv

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,genres,language,description,popularity,vote_count,vote_average
0,33238,TV Show,Running Man,안재철,"Yoo Jae-suk, Jee Seok-jin, Kim Jong-kook, Haha...",South Korea,2010-07-11,2010,8.241,1 Seasons,"Comedy, Reality",ko,A reality and competition show where members a...,1929.898,187,8.241
1,32415,TV Show,Conan,NaN,"Conan O'Brien, Andy Richter",United States of America,2010-11-08,2010,7.035,1 Seasons,"Talk, Comedy, News",en,A late night television talk show hosted by C...,1670.580,229,7.035
2,37757,TV Show,MasterChef Greece,NaN,NaN,Greece,2010-10-03,2010,5.600,1 Seasons,Reality,el,MasterChef Greece is a Greek competitive cooki...,1317.092,6,5.600
3,75685,TV Show,Prostřeno!,NaN,"Václav Vydra, Jana Boušková",Czech Republic,2010-03-01,2010,6.500,1 Seasons,Reality,cs,The knives (and forks) are out as a group of s...,1095.776,6,6.500
4,33847,TV Show,The Talk,NaN,"Amanda Kloots, Jerry O'Connell, Akbar Gbaja-Bi...","United States of America, Ireland",2010-10-18,2010,3.400,1 Seasons,Talk,en,A panel of well-known news and entertainment p...,712.070,12,3.400

In [46]:
from google.colab import files
uploaded = files.upload()
df_HBO = pd.read_csv('HBO_titles.csv')
df_HBO.head()

Saving HBO_titles.csv to HBO_titles (1).csv

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,tm155702,The Wizard of Oz,MOVIE,Young Dorothy finds herself in a magical world...,1939,G,102,"['fantasy', 'family']",['US'],NaN,tt0032138,8.1,389774.0,41.442,7.6
1,tm83648,Citizen Kane,MOVIE,"Newspaper magnate, Charles Foster Kane is take...",1941,PG,119,['drama'],['US'],NaN,tt0033467,8.3,433804.0,14.383,8.0
2,tm77588,Casablanca,MOVIE,"In Casablanca, Morocco in December 1941, a cyn...",1942,PG,102,"['drama', 'romance', 'war']",['US'],NaN,tt0034583,8.5,558849.0,20.087,8.2
3,tm82363,The Big Sleep,MOVIE,Private Investigator Philip Marlowe is hired b...,1946,NaN,116,"['thriller', 'crime']",['US'],NaN,tt0038355,7.9,84494.0,12.911,7.7
4,tm84701,The Maltese Falcon,MOVIE,A private detective takes on a case that invol...,1941,NaN,100,"['thriller', 'romance', 'crime']",['US'],NaN,tt0033870,8.0,156603.0,12.788,7.8

In [47]:
from google.colab import files
uploaded = files.upload()
df_amazon = pd.read_csv('Amazon_titles.csv')
df_amazon.head()

Saving Amazon_titles.csv to Amazon_titles (1).csv

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts20945,The Three Stooges,SHOW,The Three Stooges were an American vaudeville ...,1934,TV-PG,19,"['comedy', 'family', 'animation', 'action', 'f...",['US'],26.0,tt0850645,8.6,1092.0,15.424,7.6
1,tm19248,The General,MOVIE,"During America’s Civil War, Union spies steal ...",1926,NaN,78,"['action', 'drama', 'war', 'western', 'comedy'...",['US'],NaN,tt0017925,8.2,89766.0,8.647,8.0
2,tm82253,The Best Years of Our Lives,MOVIE,It's the hope that sustains the spirit of ever...,1946,NaN,171,"['romance', 'war', 'drama']",['US'],NaN,tt0036868,8.1,63026.0,8.435,7.8
3,tm83884,His Girl Friday,MOVIE,"Hildy, the journalist former wife of newspaper...",1940,NaN,92,"['comedy', 'drama', 'romance']",['US'],NaN,tt0032599,7.8,57835.0,11.270,7.4
4,tm56584,In a Lonely Place,MOVIE,An aspiring actress begins to suspect that her...,1950,NaN,94,"['thriller', 'drama', 'romance']",['US'],NaN,tt0042593,7.9,30924.0,8.273,7.6

In [48]:
df_netflix = pd.concat([df_netflix_movies,df_netflix_TV],axis =0)

In [49]:
df = pd.concat([df_netflix,df_amazon,df_HBO],axis =0)

In [50]:
%%markdown
---
Data Cleaning and Preprocessing

---
Data Cleaning and Preprocessing

In [51]:
df_movies = df.drop_duplicates()

In [52]:
df_movies.duplicated().sum()

np.int64(0)

In [53]:
df_movies.drop(['description', 'age_certification'], axis=1, inplace=True)

/tmp/ipykernel_11243/3930687753.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies.drop(['description', 'age_certification'], axis=1, inplace=True)

In [54]:
df_movies

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,revenue,id,runtime,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,10192.0,Movie,Shrek Forever After,Mike Mitchell,"Mike Myers, Eddie Murphy, Cameron Diaz, Antoni...",United States of America,2010-05-16,2010,6.380,NaN,...,752600867.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,27205.0,Movie,Inception,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ken W...","United Kingdom, United States of America",2010-07-15,2010,8.369,NaN,...,839030630.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,12444.0,Movie,Harry Potter and the Deathly Hallows: Part 1,David Yates,"Daniel Radcliffe, Emma Watson, Rupert Grint, T...","United Kingdom, United States of America",2010-11-17,2010,7.744,NaN,...,954305868.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,38757.0,Movie,Tangled,"Byron Howard, Nathan Greno","Mandy Moore, Zachary Levi, Donna Murphy, Ron P...",United States of America,2010-11-24,2010,7.600,NaN,...,592461732.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10191.0,Movie,How to Train Your Dragon,"Chris Sanders, Dean DeBlois","Jay Baruchel, Gerard Butler, Craig Ferguson, A...",United States of America,2010-03-18,2010,7.800,NaN,...,494879471.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3289,NaN,MOVIE,Romeo Santos: Utopia Live from MetLife Stadium,NaN,NaN,NaN,NaN,2021,NaN,NaN,...,NaN,tm1082718,103.0,['PR'],NaN,NaN,NaN,NaN,8.425,8.1
3290,NaN,MOVIE,Algo Azul,NaN,NaN,NaN,NaN,2021,NaN,NaN,...,NaN,tm1067128,90.0,['PA'],NaN,tt9257620,5.9,50.0,1.400,2.0
3291,NaN,MOVIE,Entre Nos: What She Said,NaN,NaN,NaN,NaN,2021,NaN,NaN,...,NaN,tm1121489,28.0,[],NaN,tt15532762,NaN,NaN,NaN,NaN
3292,NaN,MOVIE,Entre Nos: The Winners 2,NaN,NaN,NaN,NaN,2021,NaN,NaN,...,NaN,tm1121486,28.0,[],NaN,tt15532736,NaN,NaN,NaN,NaN
3293,NaN,MOVIE,The Infamous Future,NaN,NaN,NaN,NaN,2021,NaN,NaN,...,NaN,tm989132,40.0,['US'],NaN,tt9064760,NaN,NaN,1.101,5.3

In [79]:
df['production_countries']

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
         ...
3289    ['PR']
3290    ['PA']
3291        []
3292        []
3293    ['US']
Name: production_countries, Length: 45165, dtype: object

In [56]:
df_movies['production_countries'] = df_movies['production_countries'].str.replace(r"\[", '', regex=True).str.replace(r"'", '', regex=True).str.replace(r"\]", '', regex=True)

/tmp/ipykernel_11243/1122573671.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies['production_countries'] = df_movies['production_countries'].str.replace(r"\[", '', regex=True).str.replace(r"'", '', regex=True).str.replace(r"\]", '', regex=True)

In [57]:
df_movies['lead_prod_country'] = df_movies['production_countries'].str.split(',').str[0]

/tmp/ipykernel_11243/1598054953.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies['lead_prod_country'] = df_movies['production_countries'].str.split(',').str[0]

In [58]:
df_movies['prod_countries_cnt'] = df_movies['production_countries'].str.split(',').str.len()

/tmp/ipykernel_11243/3105672535.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies['prod_countries_cnt'] = df_movies['production_countries'].str.split(',').str.len()

In [59]:
df_movies['lead_prod_country'] = df_movies['lead_prod_country'].replace('', np.nan)

/tmp/ipykernel_11243/1718267970.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies['lead_prod_country'] = df_movies['lead_prod_country'].replace('', np.nan)

In [60]:
df_movies['lead_prod_country']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
3289     PR
3290     PA
3291    NaN
3292    NaN
3293     US
Name: lead_prod_country, Length: 45132, dtype: object

In [61]:
df_movies['genres']

0       Comedy, Adventure, Fantasy, Animation, Family
1                  Action, Science Fiction, Adventure
2                                  Adventure, Fantasy
3                        Animation, Family, Adventure
4               Fantasy, Adventure, Animation, Family
                            ...
3289                             ['romance', 'music']
3290                                       ['comedy']
3291                                       ['comedy']
3292                                       ['comedy']
3293                                ['documentation']
Name: genres, Length: 45132, dtype: object

In [62]:
df_movies['genres'] = df_movies['genres'].str.replace(r"\[", '', regex=True).str.replace(r"'", '', regex=True).str.replace(r"\]", '', regex=True)

/tmp/ipykernel_11243/3268638621.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies['genres'] = df_movies['genres'].str.replace(r"\[", '', regex=True).str.replace(r"'", '', regex=True).str.replace(r"\]", '', regex=True)

In [63]:
df_movies['main_genre'] = df_movies['genres'].str.split(',').str[0]

/tmp/ipykernel_11243/1860004975.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies['main_genre'] = df_movies['genres'].str.split(',').str[0]

In [64]:
df_movies['main_genre'] = df_movies['main_genre'].replace('', np.nan)

/tmp/ipykernel_11243/865761473.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies['main_genre'] = df_movies['main_genre'].replace('', np.nan)

In [65]:
df_movies['main_genre']

0              Comedy
1              Action
2           Adventure
3           Animation
4             Fantasy
            ...
3289          romance
3290           comedy
3291           comedy
3292           comedy
3293    documentation
Name: main_genre, Length: 45132, dtype: object

In [66]:
%%markdown
---
Drop Missing Values

---
Drop Missing Values

In [67]:
  df_movies.shape

(45132, 29)

In [68]:
df_movies.isnull().sum()

show_id                 13132
type                        0
title                       0
director                24229
cast                    14493
country                 15395
date_added              13132
release_year                0
rating                  13132
duration                29132
genres                   1081
language                13132
popularity              13132
vote_count              13132
vote_average            13132
budget                  29132
revenue                 29132
id                      32000
runtime                 32000
production_countries    32000
seasons                 43030
imdb_id                 32993
imdb_score              33393
imdb_votes              33414
tmdb_popularity         32579
tmdb_score              34345
lead_prod_country       32931
prod_countries_cnt      32000
main_genre               1343
dtype: int64

In [69]:
df_movies.dropna(inplace=True)

/tmp/ipykernel_11243/3532383511.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies.dropna(inplace=True)

In [82]:
df_movies.set_index('title', inplace=True)

In [71]:
df_movies.drop(['id', 'imdb_id'], axis=1, inplace=True)

/tmp/ipykernel_11243/1465108178.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_movies.drop(['id', 'imdb_id'], axis=1, inplace=True)

In [83]:
df_movies.head()

Empty DataFrame
Columns: [show_id, type, director, cast, country, date_added, release_year, rating, duration, genres, language, popularity, vote_count, vote_average, budget, revenue, runtime, production_countries, seasons, imdb_score, imdb_votes, tmdb_popularity, tmdb_score, lead_prod_country, prod_countries_cnt, main_genre]
Index: []

[0 rows x 26 columns]

In [80]:
print(df_movies.columns.tolist())
print(df_movies.index.name)

['show_id', 'type', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'genres', 'language', 'popularity', 'vote_count', 'vote_average', 'budget', 'revenue', 'runtime', 'production_countries', 'seasons', 'imdb_score', 'imdb_votes', 'tmdb_popularity', 'tmdb_score', 'lead_prod_country', 'prod_countries_cnt', 'main_genre']
title

In [84]:
print(df_movies.shape)

(0, 26)