<a href="https://colab.research.google.com/github/ojaspaul123/ML-Experiments/blob/main/Intros/Categorical_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('monthly_car_sales_sample.csv',usecols=['Model','Brand','Fuel_Type','Transmission'])
df.head()

Saving monthly_car_sales_sample.csv to monthly_car_sales_sample (3).csv

         Model          Brand Fuel_Type Transmission
0   i20 Sportz        Hyundai    Petrol       Manual
1    Swift VXi  Maruti Suzuki    Petrol       Manual
2     Nexon XM           Tata    Diesel       Manual
3     Creta SX        Hyundai    Petrol    Automatic
4  Baleno Zeta  Maruti Suzuki    Petrol    Automatic

In [ ]:
%%markdown
---
Using Python

---
Using Python

In [ ]:
df['Transmission'].value_counts()

Transmission
Manual       6
Automatic    4
Name: count, dtype: int64

In [ ]:
df['Transmission']= df['Transmission'].map({'Manual':1,'Automatic':2,'Semi-Auto':3})

In [ ]:
df

             Model          Brand Fuel_Type  Transmission
0       i20 Sportz        Hyundai    Petrol             1
1        Swift VXi  Maruti Suzuki    Petrol             1
2         Nexon XM           Tata    Diesel             1
3         Creta SX        Hyundai    Petrol             2
4      Baleno Zeta  Maruti Suzuki    Petrol             2
5  Punch Adventure           Tata    Petrol             1
6         Venue S+        Hyundai    Diesel             1
7      Fronx Delta  Maruti Suzuki    Petrol             2
8     Harrier Pure           Tata    Diesel             2
9     Alto K10 VXi  Maruti Suzuki    Petrol             1

In [ ]:
df['Fuel_Type']=df['Fuel_Type'].map({'Petrol':1,'Diesel':2,'Hybrid':3,'Electric':4})

In [ ]:
df

             Model          Brand  Fuel_Type  Transmission
0       i20 Sportz        Hyundai          1             1
1        Swift VXi  Maruti Suzuki          1             1
2         Nexon XM           Tata          2             1
3         Creta SX        Hyundai          1             2
4      Baleno Zeta  Maruti Suzuki          1             2
5  Punch Adventure           Tata          1             1
6         Venue S+        Hyundai          2             1
7      Fronx Delta  Maruti Suzuki          1             2
8     Harrier Pure           Tata          2             2
9     Alto K10 VXi  Maruti Suzuki          1             1

In [ ]:
df['Transmission'].apply(lambda x: 1 if x == 'Manual' else 0)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: Transmission, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('Fuel_Type',axis=1),df['Fuel_Type'],test_size=0.33,random_state=42)

In [ ]:
X_test

             Model          Brand  Transmission
8     Harrier Pure           Tata             2
1        Swift VXi  Maruti Suzuki             1
5  Punch Adventure           Tata             1
0       i20 Sportz        Hyundai             1

In [ ]:
%%markdown
---
Applying Label Encoder

---
Applying Label Encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
y_train_scal = le.fit_transform(y_train)
y_test_scal = le.fit_transform(y_test)

In [ ]:
y_test_scal

array([1, 0, 0, 0])

In [ ]:
oe = OrdinalEncoder()
X_train_scale = oe.fit_transform(X_train)
X_test_scale = oe.fit_transform(X_test)

In [ ]:
X_train_scale

array([[3., 1., 1.],
       [4., 2., 0.],
       [0., 1., 0.],
       [1., 1., 1.],
       [2., 0., 1.],
       [5., 0., 0.]])

In [ ]:
X_train.head(5)

          Model          Brand  Transmission
7   Fronx Delta  Maruti Suzuki             2
2      Nexon XM           Tata             1
9  Alto K10 VXi  Maruti Suzuki             1
4   Baleno Zeta  Maruti Suzuki             2
3      Creta SX        Hyundai             2