<a href="https://colab.research.google.com/github/ojaspaul123/ML-Experiments/blob/main/Intros/Data_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('india_covid19_data.csv')
df.head()

Saving india_covid19_data.csv to india_covid19_data.csv

   age  gender  fever cough       city has_covid
0   34    Male  101.2   Yes     Mumbai       Yes
1   27  Female   99.8    No      Delhi        No
2   45    Male  103.1   Yes  Bangalore       Yes
3   62  Female    NaN   Yes    Chennai       Yes
4   19    Male   98.6    No  Hyderabad        No

In [16]:
df.isnull().sum()
#df.shape

age          0
gender       0
fever        9
cough        0
city         0
has_covid    0
dtype: int64

In [11]:
df['cough'].value_counts()

cough
Yes    64
No     34
Name: count, dtype: int64

In [13]:
%%markdown
---
Train Test

---
Train Test

In [15]:
from sklearn.model_selection import train_test_split
X= df.drop(columns = ['has_covid'])
y= df['has_covid']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size =0.2)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((78, 5), (20, 5), (78,), (20,))

In [18]:
from sklearn.impute import SimpleImputer
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train[['fever']])
X_test_trf = si.fit_transform(X_test[['fever']])

In [19]:
X_train_trf.shape
X_test_trf.shape

(20, 1)