<a href="https://colab.research.google.com/github/ojaspaul123/ML-Experiments/blob/main/Intros/Data_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('india_covid19_data.csv')
df.head()

Saving india_covid19_data.csv to india_covid19_data.csv

   age  gender  fever cough       city has_covid
0   34    Male  101.2   Yes     Mumbai       Yes
1   27  Female   99.8    No      Delhi        No
2   45    Male  103.1   Yes  Bangalore       Yes
3   62  Female    NaN   Yes    Chennai       Yes
4   19    Male   98.6    No  Hyderabad        No

In [ ]:
df.isnull().sum()
#df.shape

age          0
gender       0
fever        9
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
df['cough'].value_counts()

cough
Yes    64
No     34
Name: count, dtype: int64

In [ ]:
%%markdown
---
without COLOUMN TRANSFORM

---
without COLOUMN TRANSFORM

In [ ]:
#train test split
from sklearn.model_selection import train_test_split
X= df.drop(columns = ['has_covid'])
y= df['has_covid']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size =0.2)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((78, 5), (20, 5), (78,), (20,))

In [ ]:
#Imputer
from sklearn.impute import SimpleImputer
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train[['fever']])
X_test_trf = si.fit_transform(X_test[['fever']])

In [ ]:
X_train_trf.shape
X_test_trf.shape

(20, 1)

In [ ]:
#Categorical Encoding
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Yes','No']])
X_train_cough = oe.fit_transform(X_train[['cough']])
X_test_cough = oe.fit_transform(X_test[['cough']])
X_train_cough.shape

(78, 1)

In [ ]:
#OneHotEncoder
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])
X_train_gender_city.shape

(78, 10)

In [ ]:
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values
X_train_age.shape

(78, 1)

In [ ]:
#Concatenate
X_train_transformed = np.concatenate((X_train_age,X_train_cough,X_train_gender_city,X_train_trf),axis =1 )
X_train_transformed

array([[ 39.        ,   1.        ,   0.        , ...,   0.        ,
          0.        ,  99.4       ],
       [ 25.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , 102.6       ],
       [ 38.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , 101.07428571],
       ...,
       [ 51.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , 103.9       ],
       [ 44.        ,   0.        ,   1.        , ...,   0.        ,
          1.        , 102.9       ],
       [ 24.        ,   1.        ,   0.        , ...,   0.        ,
          0.        ,  99.        ]])