<a href="https://colab.research.google.com/github/ojaspaul123/ML-Experiments/blob/main/Intros/OneHotEncoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('Data.csv')
df.head()

Saving Data.csv to Data.csv

,ID,FirstName,LastName,Age,Gender,Email,City,Country
0,1,Arjun,Patel,24.0,M,arjun.patel@example.com,Bhubaneswar,India
1,2,Meera,Sharma,29.0,F,meera.sharma@example.com,Delhi,India
2,3,Rahul,Verma,31.0,M,rahul.verma@example.com,Mumbai,India
3,4,Ananya,Das,22.0,F,ananya.das@example.com,Kolkata,India
4,5,Vikram,Gupta,27.0,M,vikram.gupta@example.com,Chennai,India

In [ ]:
%%markdown
---
Using Python

---
Using Python

In [ ]:
pd.get_dummies(data=df,columns=['FirstName','Gender','City'],dtype=int,drop_first='first')

,ID,LastName,Age,Email,Country,FirstName_Ananya,FirstName_Anjali,FirstName_Arjun,FirstName_Deepak,FirstName_Divya,...,City_Hyderabad,City_Jaipur,City_Kanpur,City_Kolkata,City_Lucknow,City_Mumbai,City_Patna,City_Pune,City_Shimla,City_Surat
0,1,Patel,24.0,arjun.patel@example.com,India,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Sharma,29.0,meera.sharma@example.com,India,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Verma,31.0,rahul.verma@example.com,India,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,4,Das,22.0,ananya.das@example.com,India,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,5,Gupta,27.0,vikram.gupta@example.com,India,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,6,Nair,26.0,priya.nair@example.com,India,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,7,Rao,35.0,siddharth.rao@example.com,India,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
7,8,Joshi,NaN,kavita.joshi@example.com,India,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
8,9,Kumar,30.0,manish.kumar@example.com,India,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
9,10,Choudhury,25.0,neha.choudhury@example.com,India,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
10,11,Sen,32.0,rohan.sen@example.com,India,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,12,Mishra,NaN,divya.mishra@example.com,India,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
12,13,Chopra,34.0,amit.chopra@example.com,India,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13,14,Banerjee,28.0,sneha.banerjee@example.com,India,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
14,15,Mehta,NaN,karan.mehta@example.com,India,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,16,Iyer,26.0,shreya.iyer@example.com,India,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,17,Shukla,29.0,deepak.shukla@example.com,India,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
17,18,Reddy,24.0,pooja.reddy@example.com,India,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
18,19,Thakur,33.0,nikhil.thakur@example.com,India,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
19,20,Kapoor,25.0,anjali.kapoor@example.com,India,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
%%markdown
---
With OneHotEncoder

---
With OneHotEncoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output=False)

In [ ]:
df_trans = ohe.fit_transform(df[['FirstName','Gender','City']])

In [ ]:
cols = ohe.get_feature_names_out()

In [ ]:
df_trans

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]])

In [ ]:
cols

array(['FirstName_Ananya', 'FirstName_Anjali', 'FirstName_Arjun',
       'FirstName_Deepak', 'FirstName_Divya', 'FirstName_Karan',
       'FirstName_Kavita', 'FirstName_Manish', 'FirstName_Meera',
       'FirstName_Neha', 'FirstName_Nikhil', 'FirstName_Pooja',
       'FirstName_Priya', 'FirstName_Rahul', 'FirstName_Rohan',
       'FirstName_Shreya', 'FirstName_Siddharth', 'FirstName_Sneha',
       'FirstName_Vikram', 'Gender_M', 'City_Bangalore',
       'City_Bhubaneswar', 'City_Chennai', 'City_Delhi', 'City_Guwahati',
       'City_Hyderabad', 'City_Jaipur', 'City_Kanpur', 'City_Kolkata',
       'City_Lucknow', 'City_Mumbai', 'City_Patna', 'City_Pune',
       'City_Shimla', 'City_Surat'], dtype=object)

In [ ]:
pd.DataFrame(data=df_trans,columns=cols)

,FirstName_Ananya,FirstName_Anjali,FirstName_Arjun,FirstName_Deepak,FirstName_Divya,FirstName_Karan,FirstName_Kavita,FirstName_Manish,FirstName_Meera,FirstName_Neha,...,City_Hyderabad,City_Jaipur,City_Kanpur,City_Kolkata,City_Lucknow,City_Mumbai,City_Patna,City_Pune,City_Shimla,City_Surat
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
19,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0