<a href="https://colab.research.google.com/github/ojaspaul123/ML-Experiments/blob/main/Intermmediate/Function_Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('titanic_file.csv')
df.head()

Saving titanic_file.csv to titanic_file.csv

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [5]:
df1 = pd.read_csv('titanic_file.csv',usecols = ['Age','Fare','Survived'])
df1

     Survived   Age      Fare
0           0  34.5    7.8292
1           1  47.0    7.0000
2           0  62.0    9.6875
3           0  27.0    8.6625
4           1  22.0   12.2875
..        ...   ...       ...
413         0   NaN    8.0500
414         1  39.0  108.9000
415         0  38.5    7.2500
416         0   NaN    8.0500
417         0   NaN   22.3583

[418 rows x 3 columns]

In [6]:
df1.isnull().sum()

Survived     0
Age         86
Fare         1
dtype: int64

In [8]:
df1['Age'].fillna(df1['Age'].mean(), inplace=True)
df1['Fare'].fillna(df1['Fare'].mean(), inplace=True)

/tmp/ipykernel_9831/3076764914.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Age'].fillna(df1['Age'].mean(), inplace=True)
/tmp/ipykernel_9831/3076764914.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Fare'].fillna(df1['Fare'].mean(), inplace=True)

In [9]:
X = df1.iloc[:,1:3]
y = df.iloc[:,0]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)